name: Deploy to AWS Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build --if-present

      - name: Print github.sha
        run: echo ${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Beanstalk
        id: deploy
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name exp-server \
            --version-label v${{ github.sha }} \
            --source-bundle "S3Bucket=elasticbeanstalk-us-east-1-768519948299,S3Key='1686089249254-basic-express-server-main (8).zip'"
          aws elasticbeanstalk update-environment \
            --environment-name Exp-server-env \
            --version-label v${{ github.sha }}

      - name: Set deployment status
        run: echo "DEPLOYMENT_STATUS=success" >> $GITHUB_ENV

      - name: Display deployment status
        run: |
          echo "Deployment status: $DEPLOYMENT_STATUS"
        env:
          DEPLOYMENT_STATUS: ${{ env.DEPLOYMENT_STATUS }}

      - name: Run tests
        run: npm test
